
package AFS.FrontEnd;

import AFS.Models.result;
import AFS.ServiceLayer.resultServiceLayer;
import javax.swing.JOptionPane;

/**
 * Question 2 GUI (JFrame)
 * @author Malindu Ransara Nawarathne
 */
public class question2 extends javax.swing.JFrame {

    /**
     * Creates new form question1
     */
    public question2() {
        initComponents();
        //To center the current window in the display
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        answer1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnPunctual = new javax.swing.JRadioButton();
        btnSLate = new javax.swing.JRadioButton();
        btnLate = new javax.swing.JRadioButton();
        btnELate = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        exitIcon = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Question 2:");
        jLabel1.setToolTipText("");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Did the driver arrive at time?");

        btnPunctual.setBackground(new java.awt.Color(51, 51, 51));
        answer1.add(btnPunctual);
        btnPunctual.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnPunctual.setForeground(new java.awt.Color(255, 255, 255));
        btnPunctual.setText("Punctual");

        btnSLate.setBackground(new java.awt.Color(51, 51, 51));
        answer1.add(btnSLate);
        btnSLate.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnSLate.setForeground(new java.awt.Color(255, 255, 255));
        btnSLate.setText("Slightly Late");

        btnLate.setBackground(new java.awt.Color(51, 51, 51));
        answer1.add(btnLate);
        btnLate.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnLate.setForeground(new java.awt.Color(255, 255, 255));
        btnLate.setText("Late");

        btnELate.setBackground(new java.awt.Color(51, 51, 51));
        answer1.add(btnELate);
        btnELate.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnELate.setForeground(new java.awt.Color(255, 255, 255));
        btnELate.setText("Extremely Late");

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton1.setText("Next");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        exitIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AFS/Resources/Exit_45px.png"))); // NOI18N
        exitIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitIconMouseClicked(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnPunctual)
                                .addGap(18, 18, 18)
                                .addComponent(btnSLate)
                                .addGap(18, 18, 18)
                                .addComponent(btnLate)
                                .addGap(18, 18, 18)
                                .addComponent(btnELate))
                            .addComponent(jLabel2)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(exitIcon)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 563, Short.MAX_VALUE)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(50, 50, 50)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(60, 60, 60))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(jLabel1)
                .addGap(45, 45, 45)
                .addComponent(jLabel2)
                .addGap(61, 61, 61)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPunctual)
                    .addComponent(btnSLate)
                    .addComponent(btnLate)
                    .addComponent(btnELate))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 137, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(exitIcon)
                        .addGap(60, 60, 60))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(jButton2))
                        .addGap(60, 60, 60))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // To submit question 2 answers
        
        //Initializing and declaring variable
        boolean ansStatus = false;
        String ansValue = "";
        
        //Fetching selected values
        if ( btnPunctual.isSelected() )
        {
            System.out.println("Puntual");
            ansStatus = true;
            ansValue = "Punctual";
        } else if ( btnSLate.isSelected() ) {
            System.out.println("Slightly Late");
            ansStatus = true;
            ansValue = "Slightly Late";
        } else if ( btnLate.isSelected() ) {
            System.out.println("Late");
            ansStatus = true;
            ansValue = "Late";
        } else if ( btnELate.isSelected() ) {
            System.out.println("Extremely Late");
            ansStatus = true;
            ansValue = "Extremely Late";
        } else {
            System.out.println("Empty");
            ansStatus = false;
            ansValue = "Empty";
        }
        
        // Validating the whether the value is selected or not
         if ( ansStatus == true ) {
            result rs2 = new result ( 2, ansValue );
            resultServiceLayer restsl = new resultServiceLayer();
            restsl.saveAnswer ( rs2, 2 );
            new question3().setVisible(true);
            this.dispose();
         } else {
            JOptionPane.showMessageDialog(this, "Please Select an Answer!", "Error!", 2);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void exitIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitIconMouseClicked
        // To terminate application
        System.exit(0);
    }//GEN-LAST:event_exitIconMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // To return to question 1 window
        new question1().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(question2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(question2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(question2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(question2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new question2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup answer1;
    private javax.swing.JRadioButton btnELate;
    private javax.swing.JRadioButton btnLate;
    private javax.swing.JRadioButton btnPunctual;
    private javax.swing.JRadioButton btnSLate;
    private javax.swing.JLabel exitIcon;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
